# Generated by Django 5.2.1 on 2025-06-02 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='venda',
            old_name='data',
            new_name='data_venda',
        ),
        migrations.RenameField(
            model_name='venda',
            old_name='total',
            new_name='valor_total',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='usuario',
        ),
        migrations.AddField(
            model_name='produto',
            name='alerta_minimo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='venda',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendas', to='core.produto'),
        ),
        migrations.AddField(
            model_name='venda',
            name='quantidade',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venda',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='produto',
            name='estoque',
            field=models.IntegerField(),
        ),
    ]
